### PR TITLE
Improve Packaging

### LINKED ISSUE #71: The log files folder is incorrectly created relative to the CWD
When calling `bin/ctd-omega-services` the log files folder is incorrectly created relative to the CWD (current working directory).

This is especially a problem when trying to deploy the packages application on a server, and yields startup errors like:
```
12:43:02,754 |-INFO in ch.qos.logback.classic.LoggerContext[default] - This is logback-classic version 1.3.11
12:43:02,757 |-INFO in ch.qos.logback.classic.util.ContextInitializer@66c92293 - No custom configurators were discovered as a service.
12:43:02,757 |-INFO in ch.qos.logback.classic.util.ContextInitializer@66c92293 - Trying to configure with ch.qos.logback.classic.joran.SerializedModelConfigurator
12:43:02,758 |-INFO in ch.qos.logback.classic.util.ContextInitializer@66c92293 - Constructed configurator of type class ch.qos.logback.classic.joran.SerializedModelConfigurator
12:43:02,778 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.scmo]
12:43:02,779 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.scmo]
12:43:02,780 |-INFO in ch.qos.logback.classic.util.ContextInitializer@66c92293 - ch.qos.logback.classic.joran.SerializedModelConfigurator.configure() call lasted 22 milliseconds. ExecutionStatus=INVOKE_NEXT_IF_ANY
12:43:02,780 |-INFO in ch.qos.logback.classic.util.ContextInitializer@66c92293 - Trying to configure with ch.qos.logback.classic.util.DefaultJoranConfigurator
12:43:02,780 |-INFO in ch.qos.logback.classic.util.ContextInitializer@66c92293 - Constructed configurator of type class ch.qos.logback.classic.util.DefaultJoranConfigurator
12:43:02,781 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
12:43:02,784 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/usr/share/ctd-omega-services/lib/uk.gov.nationalarchives.ctd-omega-services-0.1.0-SNAPSHOT.jar!/logback.xml]
12:43:02,790 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@332796d3 - URL [jar:file:/usr/share/ctd-omega-services/lib/uk.gov.nationalarchives.ctd-omega-services-0.1.0-SNAPSHOT.jar!/logback.xml] is not of type file
12:43:02,988 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [STDOUT]
12:43:02,988 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
12:43:02,995 |-INFO in ch.qos.logback.core.model.processor.ImplicitModelHandler - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
12:43:03,042 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [FILE]
12:43:03,042 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.FileAppender]
12:43:03,277 |-INFO in ch.qos.logback.core.FileAppender[FILE] - File property is set to [logs/ctd-omega-services.log]
12:43:03,279 |-ERROR in ch.qos.logback.core.FileAppender[FILE] - openFile(logs/ctd-omega-services.log,true) call failed. java.io.FileNotFoundException: logs/ctd-omega-services.log (Permission denied)
        at java.io.FileNotFoundException: logs/ctd-omega-services.log (Permission denied)
        at      at java.base/java.io.FileOutputStream.open0(Native Method)
        at      at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
        at      at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
        at      at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:26)
        at      at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:206)
        at      at ch.qos.logback.core.FileAppender.start(FileAppender.java:126)
```

# Observed

## Example 1:
```bash
cd /tmp
ctd-omega-services-0.1.0-SNAPSHOT/bin/ctd-omega-services
```
This creates the log files folder: `/tmp/logs`

## Example 2:
```bash
cd /tmp/ctd-omega-services-0.1.0-SNAPSHOT
bin/ctd-omega-services
```
This creates the log files folder: `/tmp/ctd-omega-services-0.1.0-SNAPSHOT/logs`

## Example 3:
```bash
cd /tmp/ctd-omega-services-0.1.0-SNAPSHOT/bin
./ctd-omega-services
```
This creates the log files folder: `/tmp/ctd-omega-services-0.1.0-SNAPSHOT/bin/logs`

----
# Triage

This occurs because a `logback.xml` file is packaged inside the jar file because it is present in the project's `src/main/resources` folder. That `logback.xml` file contains the relative path for the log file as: `<file>logs/ctd-omega-services.log</file>`.

----
# Expected
1. The log files folder should always be created at `ctd-omega-services-0.1.0-SNAPSHOT/log`
2. The user should be able to configure and or override the logging.

### LINKED ISSUE #72: The temp messages folder is incorrectly created relative to the CWD
Similar to https://github.com/nationalarchives/ctd-omega-services/issues/71 except that the relative path for `temp-messages` folder is hardcoded in https://github.com/nationalarchives/ctd-omega-services/blob/3f2f98a21d0891f8151c8d374b717a5fc0505f54/src/main/scala/uk/gov/nationalarchives/omega/api/services/ApiService.scala#L115 i.e.:
```scala
val messageStoreFolder = Paths.get(config.tempMessageDir)
```

### PR DESCRIPTION
**Pull request by adamretter**
* Enable the JMS Broker connection settings to be configured through `application.conf`.
* Document the `application.conf` settings file.
* Allows `application.conf` (inside the Jar file) to be overridden by `settings.conf` (now) shipped with the package.
* Add a target to build an RPM package (for use in AWS).
* Allows the location of the log files to be configured externally (defaults to: `log/ctd-omega-services.log` relative to the package).
* Allows the location of the message store to be configured externally (defaults to: `data/message-store` relative to the package).

Closes https://github.com/nationalarchives/ctd-omega-services/issues/71
Closes https://github.com/nationalarchives/ctd-omega-services/issues/72

### CODE REVIEW

**Review by rwalpole — APPROVED** [review]
LGTM @adamretter - however you have a compilation error in `MessageRecoveryISpec`. Looks like a parameter name has changed.

**Comment by adamretter** [comment]
> however you have a compilation error in MessageRecoveryISpec

@rwalpole Should all be fixed now.

**Review by rwalpole — APPROVED** [review]

**Comment by rwalpole** [comment]
@adamretter is this ready to be merged now?

**Comment by adamretter** [comment]
@rwalpole Yes I think so - but with the caveat that we may need to update the `application.conf` for Neptune still due to the connectivity issue we were seeing.

**Pull request merged**
