### PR TITLE
PACT-1028: fixing typos and updating queue names

### PR DESCRIPTION
**Pull request by rwalpole**

### CODE REVIEW

**Review by adamretter — COMMENTED** [review]
Thanks for fixing my typos and spelling mistakes :-)

I am just wondering where your proposed Channel naming has come from?

I think your proposal is:

* `PACS001_request` for the *general* request queue of the `ctd-omega-services` application
* `PACE001_reply` for the reply queue of the `ctd-omega-editorial-frontend` application

I see further down however in this document:
```yaml
examples:
  - 'PACE001_REPLY_1'
  - 'OMGR002_REPLY'
```

Which makes me wonder what we should call these things... I doubt that I have recorded names for these anywhere else. I think names inspired by those two approaches would make sense perhaps, i.e. how about this:

* `PACS001_REQUEST001`
* `PACE001_REPLY001`

The first part `PACS001` or `PACE001` can then follow the format of the `OMGApplicationID Header`

**Comment by rwalpole** [comment]
@adamretter I can leave the channel naming out of this PR if you prefer - I just amended it because it was clearly wrong. The queues we currently have set up are:
- `PACS001_request` - for request messages to the API Services.
- `PACE001_reply` - for reply messages to the editorial frontend.
- `STUB001_request` - for request messages to the stub server.
As you say, the format of the first part is mandated by the regex for the `OMGapplicationID`. In the second part I just took the minimal approach, but I don't know how many such queues we could have per application. If there is more than one then definitely we should number them.

**Comment by adamretter** [comment]
@rwalpole I have updated the queue names as I described. Let me know that you are happy with that, and if so, I will get this merged...

**Comment by rwalpole** [comment]
@adamretter queue names LGTM

**Pull request merged**
